-- Local Tourist Day-Visit Planner - seed data
-- ITE2953, J A S R Perera (E2410994)
-- Source: docs/places-data.xlsx (verified place data sheet). Run AFTER schema.sql.
-- distance_km holds the approximate SRS distance for now; it is replaced with the
-- OSRM road distance from Salgas Junction when route support is built (FR-47).
USE mattegoda_planner;
SET NAMES utf8mb4;
START TRANSACTION;

-- 1. Categories (7, BR-02)
INSERT INTO category (category_id, name, badge_colour, marker_icon) VALUES
  (1, 'religious', '#8E24AA', 'marker-religious.png'),
  (2, 'natural', '#2E7D32', 'marker-natural.png'),
  (3, 'heritage', '#795548', 'marker-heritage.png'),
  (4, 'cultural', '#EF6C00', 'marker-cultural.png'),
  (5, 'recreational', '#1E88E5', 'marker-recreational.png'),
  (6, 'dining', '#C62828', 'marker-dining.png'),
  (7, 'public', '#546E7A', 'marker-public.png');

-- 2. Places (14, all within 25 km of Salgas Junction, BR-01)
INSERT INTO place (place_id, name, summary, description, latitude, longitude, access_point, opening_time, closing_time, closed_days, entry_fee, best_time, visit_duration_min, travel_tips, facilities, distance_km, travel_min, info_source) VALUES
  (1, 'Gammanaya Restaurant, Makumbura', 'A casual local dining spot on High Level Road serving traditional Sri Lankan rice and curry alongside quick short eats.', 'Traditional village-style Sri Lankan restaurant near the Kottawa expressway interchange, serving authentic rice and curry in a rustic setting.', 6.839569, 79.975148, 'Main Entrance (High Level Road)', '07:00:00', '22:00:00', '', 'Rs. 500 - 1,000 (approx. per person)', 'Lunch (11:30 am–2:00 pm) or dinner (7:00–9:30 pm)', 60, 'Arrive early during peak lunchtime to secure seating. On-site vehicle parking is available directly at the High Level Road entrance. Open until 23:00 on Sundays.', 'Parking, dining area, takeaway service, restrooms', 3.0, NULL, 'https://lk.near-place.com/gammanaya-kottawa-town-pannipitiya'),
  (2, 'Bolgoda Lake, Piliyandala', 'Sri Lanka''s largest natural lake, a partly brackish estuary popular for leisurely boat rides, birdwatching and waterside dining.', 'Sri Lanka''s largest natural lake, a semi-closed brackish estuarine system popular for boat rides, birdwatching and lakeside relaxation.', 6.775397, 79.904228, NULL, '06:00:00', '18:00:00', '', 'Free', 'Late afternoon (4:00–6:00 pm) for sunset and boat rides', 90, 'Boat rides are run by private operators along the shore. Bring sun protection and insect repellent for time on the water.', 'Boat rides (private operators), scenic viewpoints, roadside parking', 10.0, NULL, 'https://www.cea.lk/web/?option=com_content&view=article&layout=edit&id=1806'),
  (3, 'Diyasaru Park, Thalawathugoda', 'A 60-acre urban wetland nature park with walking trails, an observation tower, boat rides and rich native biodiversity.', 'Urban wetland park with wooden boardwalks, a birdwatching tower and rich biodiversity, including endemic butterflies.', 6.879536, 79.928933, 'Main visitor entrance gate (Friendship Rd)', '06:00:00', '18:00:00', '', 'Rs. 100 (local), Rs. 500 (foreign)', 'Early morning (6:00–9:00 am) for birdwatching', 90, 'Enter via the main gate on Japan–Sri Lanka Friendship Road; tickets stop at 5:00 pm. Wear sturdy walking shoes, and note that single-use plastic bottles are prohibited on the trails. Boat rides cost about Rs. 750 per ride.', 'Parking, restrooms (wheelchair accessible), observation tower, walking trails, boat rides', 10.0, NULL, 'https://diyasarupark.lk/'),
  (4, 'Bellanwila Rajamaha Viharaya', 'A historic Buddhist temple revered for its sacred Bodhi tree, serene monastic courtyards, and detailed temple wall murals.', 'Historic Buddhist temple with a sacred Bo tree believed to be a sapling of the Sri Maha Bodhi; famous for its annual perahera.', 6.845187, 79.890013, NULL, '06:00:00', '21:00:00', '', 'Free', 'Early morning (6:30–8:30 am) or evening (5:30–7:30 pm) during pooja', 45, 'Wear modest clothing that covers shoulders and knees, and remove footwear before stepping into the inner courtyard.', 'Parking, restrooms, flower stalls, shoe storage', 12.0, NULL, 'https://temple.yatradham.org/temple/bellanwila-rajamaha-viharaya-dehiwala'),
  (5, 'Attidiya Bird Sanctuary', 'A protected urban wetland sanctuary home to numerous resident and migratory waterfowl, butterflies, and aquatic wildlife.', 'Protected urban wetland sanctuary ideal for birdwatching; best visited in the early morning.', 6.837299, 79.890525, 'Information centre (start of main trail)', '09:00:00', '17:00:00', 'Sun', 'Free', 'Morning (9:00-11:00 am) for active birdlife', 75, 'The main trail starts beside the information centre and follows the Bolgoda Canal out to Attidiya Road, with a viewing tower about halfway. Bring insect repellent, wear closed-toe shoes and keep noise to a minimum. Hours are for the information centre (Mon-Sat); it is closed on Sundays.', 'Walking trail, viewing tower, information centre', 12.0, NULL, 'https://touristboard.wp.gov.lk/destination.php?destid=120'),
  (6, 'Apē Gama, Battaramulla', 'A cultural heritage theme park replicating a traditional Sri Lankan village, complete with rural homes and live craft demonstrations.', 'Recreated traditional Sri Lankan village showcasing rural life, crafts and culture.', 6.890757, 79.922442, 'Main entrance gate (Jana Kala Kendraya)', '09:00:00', '21:00:00', '', 'Rs. 100 (local); higher rate for foreigners', 'Morning (9:30–11:30 am) or late afternoon (4:00–6:00 pm)', 90, 'Enter through the main Jana Kala Kendraya gate. Wear comfortable shoes for the unpaved gravel paths and carry cash for the artisan craft stalls.', 'Parking, restrooms, craft stalls, restaurant', 12.0, NULL, 'http://craftscouncil.gov.lk/venue/ape-gama/'),
  (7, 'Beddagana Wetland Park, Kotte', 'A peaceful nature reserve featuring elevated timber boardwalks traversing lush marshes, duck ponds, and bird habitats.', 'An 18-hectare swamp-forest park with boardwalk trails within the area of the historic Kotte kingdom, opened to the public in 2016.', 6.890731, 79.906439, 'Car park, 139 Rampart Road, Kotte', '06:00:00', '18:00:00', 'Poya', 'Rs. 100 (local), Rs. 1,000 (foreign)', 'Early morning (6:30–9:00 am) or late afternoon (3:30–5:30 pm)', 90, 'Tickets are cash only and parking costs Rs. 50. Plastic items are banned inside the park, so bring a reusable glass or metal water bottle. Ticket issuing stops around 17:30. Closed on Poya days.', 'Parking, restrooms, boardwalk trails, bird observation tower, educational centre', 14.0, NULL, 'https://www.facebook.com/beddaganawetlandpark'),
  (8, 'Diyatha Uyana, Battaramulla', 'A vibrant waterfront public park and promenade on Diyawanna Lake featuring food vendors, walking tracks, and plant nurseries.', 'Lakeside public park beside the Parliament with boat rides, a food court and a plant and flower market.', 6.90423, 79.909949, 'Polduwa Junction main pedestrian entrance', '06:00:00', '22:00:00', '', 'Free', 'Late afternoon to evening (5:00–8:00 pm)', 75, 'Enter from Polduwa Junction near the Waters Edge hotel. Parking is available on-site, and visiting after sunset lets you enjoy the fountains and evening stalls.', 'Parking, restrooms, food stalls, walking path, children''s play area, boat rides', 15.0, NULL, 'https://www.travelmapsrilanka.com/destinations/diyatha-uyana.php'),
  (9, 'Dehiwala Zoological Gardens', 'Sri Lanka''s oldest zoo, open since 1936, with a large collection of native and exotic mammals, birds and reptiles, plus an aquarium.', 'The national zoo of Sri Lanka, housing a wide collection of animals, birds and reptiles; a reliable half-day attraction.', 6.856397, 79.872669, 'Main entrance ticket gate (Anagarika Dharmapala Mw)', '08:30:00', '17:00:00', '', 'Rs. 295 (local), USD 17.70 (foreign)', 'Morning (8:30–11:00 am) during animal feedings', 180, 'Enter via the main ticket gate on Anagarika Dharmapala Mawatha. Plastic, polythene and pets are not allowed inside. Bring an umbrella, a sunhat and plenty of water for the long outdoor walkways.', 'Parking, restrooms, cafes, souvenir shops, first aid, wheelchair access', 15.0, NULL, 'https://nationalzoo.gov.lk/dehiwala-zoo/'),
  (10, 'Mount Lavinia Beach', 'A celebrated stretch of golden coastline known for colonial beachfront dining, sunset strolls, and relaxing ocean views.', 'The most popular beach in the Colombo area, known for sunset views and beachside seafood restaurants.', 6.838435, 79.863374, 'College Avenue coastal public access', '00:00:00', '23:59:00', '', 'Free', 'Late afternoon to sunset (5:00–6:30 pm)', 90, 'Access the shoreline from College Avenue. Exercise caution when swimming due to seasonal currents, and head over around sunset for beachfront seafood dining.', 'Lifeguard stations, beach restaurants, roadside parking, changing stalls', 15.0, NULL, 'https://tourstro.com/blogs/mount-lavinia-beach'),
  (11, 'Independence Square, Colombo', 'A monumental open-air hall commemorating Sri Lankan independence, surrounded by manicured lawns and popular fitness pathways.', 'National monument commemorating the independence of Sri Lanka in 1948, surrounded by an open public space.', 6.904384, 79.867819, 'North promenade access (Independence Avenue)', '00:00:00', '23:59:00', '', 'Free', 'Early morning (6:30–8:30 am) or evening (5:00–7:30 pm)', 45, 'Enter from the north promenade on Independence Avenue. Paved pathways make it suitable for jogging or strollers, and vehicle parking is available in adjacent lots. The basement Independence Memorial Museum is open 09:00-17:00, closed Sundays, Mondays and public holidays (Rs. 50 local, about Rs. 500-600 foreign).', 'Paved walkways, benches, restrooms, nearby parking, museum', 19.0, NULL, 'https://www.lakpura.com/pages/independence-memorial-hall'),
  (12, 'Colombo National Museum', 'Sri Lanka''s largest museum, displaying regalia from the Kandyan kingdom, ancient stone sculptures, and historical artifacts.', 'The largest museum in the country, exhibiting royal artefacts, ancient art and archaeological collections.', 6.909889, 79.860783, 'Main visitor gate (Sir Marcus Fernando Mw)', '09:00:00', '18:00:00', 'Mon,Poya', 'Rs. 100 (local), Rs. 1,200 (foreign)', 'Morning (9:30 am–12:30 pm) to avoid crowds', 120, 'Enter through the main gate on Sir Marcus Fernando Mawatha (Albert Crescent). Ticket sales end at 15:00, so arrive early. A camera permit (Rs. 250) is sold at the counter. Closed on Mondays and public holidays, including Poya days, which change monthly.', 'Parking, restrooms, gift shop, cafe, ticket counter', 20.0, NULL, 'https://www.newswire.lk/2025/08/13/museums-new-opening-and-closing-days-times-announced/'),
  (13, 'Viharamahadevi Park, Colombo', 'Colombo''s premier colonial-era central park, boasting wide tree-lined promenades, flowering gardens, fountains, and a Buddha statue.', 'The largest public park in Colombo, located beside the Town Hall, with walking paths, statues and a children''s play area.', 6.915089, 79.863166, 'Northern entrance opposite Town Hall (by Buddha statue)', '00:00:00', '23:59:00', '', 'Free', 'Early morning (6:30–9:00 am) or late afternoon (4:30–6:00 pm)', 60, 'Enter at the northern end opposite Colombo Town Hall, beside the large Buddha statue. Tree-shaded benches are spread throughout the gardens, making it ideal for a morning or late-afternoon visit.', 'Restrooms, children''s play area, walking paths, open-air amphitheatre, parking', 20.0, NULL, 'https://srilanka.travel/attraction?attraction_id=216'),
  (14, 'Colombo Lotus Tower', 'South Asia''s tallest self-supported tower, featuring high-speed elevators, an observation deck, and 360-degree city views.', 'The tallest tower in South Asia, with a 360-degree observation deck offering panoramic views of Colombo and the coastline.', 6.927668, 79.85884, 'Main ticketing pavilion (D. R. Wijewardena Mw)', '09:00:00', '22:00:00', '', 'Rs. 500 (local), USD 20 (foreign)', 'Sunset to evening (5:30–8:00 pm) for city lights', 75, 'Enter via the main ticketing pavilion on D. R. Wijewardena Mawatha. Book online to skip the counter queue and carry your NIC or driving licence, since local rates need matching ID. Tickets are sold until 21:00 on weekdays and 22:00 at weekends, when the tower stays open until 23:00. The Blue Orbit revolving restaurant needs a booking (buffet about Rs. 9,000-10,000).', 'Parking, restrooms, elevators, observation deck, Blue Orbit revolving restaurant, gift shop', 22.0, NULL, 'https://tickets.colombolotustower.lk/');

-- 3. Category assignments (M:N, FR-08). is_primary = 1 drives the map marker (FR-20)
INSERT INTO place_category (place_id, category_id, is_primary) VALUES
  (1, 6, 1),
  (2, 2, 1),
  (3, 2, 1),
  (4, 1, 1),
  (5, 2, 1),
  (6, 4, 1),
  (7, 2, 1),
  (8, 5, 1),
  (9, 5, 1),
  (10, 2, 1),
  (10, 5, 0),
  (11, 3, 1),
  (12, 3, 1),
  (13, 7, 1),
  (13, 5, 0),
  (14, 7, 1);

-- 4. Photos (credit stored in source, SRS 6.3). Places without a row show the placeholder (FR-14)
INSERT INTO place_photo (place_id, file_path, caption, source, sort_order) VALUES
  (2, 'uploads/places/bolgoda-lake-1.jpg', 'Bolgoda Lake, Piliyandala', 'Wikimedia Commons, Kaveen Weerarathna, CC BY-SA 4.0, https://commons.wikimedia.org/wiki/File:Bolgoda_Lake,_Sri_Lanka.jpg', 1),
  (3, 'uploads/places/diyasaru-park-1.jpg', 'Diyasaru Park, Thalawathugoda', 'Wikimedia Commons, Randikachat, CC BY-SA 4.0, https://commons.wikimedia.org/wiki/File:Diyasaru.jpg', 1),
  (4, 'uploads/places/bellanwila-temple-1.jpg', 'Bellanwila Rajamaha Viharaya', 'Wikimedia Commons, Sachindu 5, CC BY-SA 4.0, https://commons.wikimedia.org/wiki/File:Bellanvila_temple.jpg', 1),
  (5, 'uploads/places/attidiya-sanctuary-1.jpg', 'Attidiya Bird Sanctuary', 'Wikimedia Commons, Udendra Geeganage, CC BY-SA 4.0, https://commons.wikimedia.org/wiki/File:Bellanwila-Attidiya_Sanctuary.jpg', 1),
  (7, 'uploads/places/beddagana-wetland-1.jpg', 'Beddagana Wetland Park, Kotte', 'Wikimedia Commons, Salithak1, CC BY-SA 4.0, https://commons.wikimedia.org/wiki/File:Beddagana_wetland_park.jpg', 1),
  (8, 'uploads/places/diyatha-uyana-1.jpg', 'Diyatha Uyana, Battaramulla', 'Wikimedia Commons, Hansa Nanayakkara, CC BY-SA 3.0, https://commons.wikimedia.org/wiki/File:Fountain_at_Diyatha_Uyana.JPG', 1),
  (9, 'uploads/places/dehiwala-zoo-1.jpg', 'Dehiwala Zoological Gardens', 'Wikimedia Commons, A-wiki-guest-user, CC BY-SA 4.0, https://commons.wikimedia.org/wiki/File:Dehiwala_Zoo_Museum.jpg', 1),
  (10, 'uploads/places/mount-lavinia-beach-1.jpg', 'Mount Lavinia Beach', 'Wikimedia Commons, Honeplus, CC BY-SA 3.0, https://commons.wikimedia.org/wiki/File:Mount_Lavinia_Beach_in_Sri_Lanka.jpg', 1),
  (11, 'uploads/places/independence-square-1.jpg', 'Independence Square, Colombo', 'Wikimedia Commons, Charaka Ranasinghe, CC BY 2.0, https://commons.wikimedia.org/wiki/File:Independence_Commemoration_Hall.jpg', 1),
  (12, 'uploads/places/national-museum-1.jpg', 'Colombo National Museum', 'Wikimedia Commons, Hasindu2008, CC BY-SA 3.0, https://commons.wikimedia.org/wiki/File:Colombo_National_Museum_Sri_Lanka.JPG', 1),
  (13, 'uploads/places/viharamahadevi-park-1.jpg', 'Viharamahadevi Park, Colombo', 'Wikimedia Commons, A.Savin, Free Art License, https://commons.wikimedia.org/wiki/File:SL_Colombo_asv2020-01_img11_Viharamahadevi_Park.jpg', 1),
  (14, 'uploads/places/lotus-tower-1.jpg', 'Colombo Lotus Tower', 'Wikimedia Commons, Nisal Senanayaka, CC BY-SA 4.0, https://commons.wikimedia.org/wiki/File:Nelum_kuluna_lotus_tower_wide_angle_view.jpg', 1);

COMMIT;

-- The administrator account is NOT seeded here: create it with
-- database/create_admin.php so the password is hashed with password_hash() (FR-38, NFR-09).
